import Head from 'next/head'
import Vibes from '../components/Containers/Vibes'
import Layout from '../components/Layout/Layout'
import ResidentialCleaning from '../components/Containers/Residential'
import GiftPoints from '../components/Containers/GiftPoints'
import { useState } from 'react'

export default function Home() {

  const [enabled, setEnabled] = useState(false)

  return (
    <>
      <Head>
        <title>Yeah Of Course | YOF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout enabled={enabled} setEnabled={setEnabled}>
        <main className={`${enabled === true && 'dark'}`}>
          <section className='pb-12 dark:bg-black'>
          <Vibes enabled={enabled} setEnabled={setEnabled} />
          <ResidentialCleaning />
          <GiftPoints />
          </section>
        </main>
      </Layout>
    </>
  )
}
