import Head from 'next/head'
import Vibes from '../components/Containers/Vibes'
import Layout from '../components/Layout/Layout'
import ResidentialCleaning from '../components/Containers/Residential'
import GiftPoints from '../components/Containers/GiftPoints'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  let getItem;
  let value
  if (typeof window !== 'undefined') {
    getItem = localStorage.getItem('mode')
    if (getItem === null) {
      localStorage.setItem('mode', JSON.stringify(false))
    }
  }

  let [enabled, setEnabled] = useState(value)
  const router = useRouter();
  const { locale } = router;

  if (typeof window !== 'undefined') {
    localStorage.setItem('mode', enabled)
  }
  useEffect(() => {
    if (getItem === 'true') {
      setEnabled(true)
    } else {
      setEnabled(false)
    }
  }, [])

  return (
    <>
      <Head>
        <title>Yeah Of Course | YOF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout locale={locale} enabled={enabled} setEnabled={setEnabled}>
        <main className={`${enabled === true && 'dark transition ease-in-out delay-150'}`}>
          <section className='pb-12 dark:bg-black'>
            <Vibes locale={locale} enabled={enabled} setEnabled={setEnabled} />
            <ResidentialCleaning locale={locale} enabled={enabled} />
            <GiftPoints locale={locale} enabled={enabled} />
          </section>
        </main>
      </Layout>
    </>
  )
}
